In [3]:
using LinearAlgebra
using Random


# Arrays
------

Julia has built-in support for
many types of collection.  Arrays
are used for rank-n tensors.
A column vector is created using
square bracket notation.
Elements are separated by commas.


In [4]:
[1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

A row vector is created by placing
spaces between elements.

In [5]:
[1 2 3]

1×3 Matrix{Int64}:
 1  2  3

A rank-2 tensor is created as row
vector, separated by a semi-colon.

In [6]:
[1 2 3; 4 5 6]


2×3 Matrix{Int64}:
 1  2  3
 4  5  6

Column vector in a matrix are created
as nested arrays, with a space between
each column vector.



In [7]:
[[1, 2, 3] [4, 5, 6]]

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

### Julia has a hierarchical type structure.


In [8]:
typeof([[1, 2, 3] [4, 5, 6]]) #The typoeof() function returns the type of an object.

Matrix{Int64} (alias for Array{Int64, 2})

In [9]:
supertype(Array) # The supertype function returns the parent of the given type.


DenseArray

In [10]:
supertype(DenseArray)


AbstractArray

All types are subtypes of the Any type.
The subtypes() function return the
children of the given type.

In [11]:
supertype(AbstractArray)


Any

We note that there are 31 children of the
AbstractArray type.

The leaves of this hierarchical structure
are the concrete types and only they
can be instantiated.


### Useful constructors
 -------------------

There are many useful functions to construct arrays.


In [12]:
ones(3, 3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [13]:
zeros(5)

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [14]:
falses(3)

3-element BitVector:
 0
 0
 0

In [15]:
trues(3)


3-element BitVector:
 1
 1
 1

There are built-in iterators.  Since the
code is compiled, loops are not always
slower than vectorized code.  List
comprehension is a great way to create
an array

In [16]:
[i^2 for i = 1:5]


5-element Vector{Int64}:
  1
  4
  9
 16
 25

Below, we construct a vector of
(immutable) tuples.

In [17]:
[(i, j) for i = 1:2 for j = 1:3]


6-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (1, 2)
 (1, 3)
 (2, 1)
 (2, 2)
 (2, 3)

An upper or lower triangular view of
a matrix can be created.  First, we seed
the pseudo-random number generator.

In [18]:
Random.seed!(12);

In [19]:
A = rand(1:10, 5, 5)


5×5 Matrix{Int64}:
  4  2  9  8  3
 10  1  7  3  9
  6  8  8  7  4
 10  5  9  8  2
  4  7  9  2  8

An upper triangular view of A.  This is not factorization.

In [20]:
t = UpperTriangular(A)


5×5 UpperTriangular{Int64, Matrix{Int64}}:
 4  2  9  8  3
 ⋅  1  7  3  9
 ⋅  ⋅  8  7  4
 ⋅  ⋅  ⋅  8  2
 ⋅  ⋅  ⋅  ⋅  8

Note that the matrix has two ways of indexation. First you can address the element as usual by chosin two numbers (i, j). But also, all the elements are numbered as they are in a onedimensional array composed of concatenated matrix columns, compare t[1,3] and t[11]

In [21]:
t[1,3] == t[11]

true

A lower triangular view of A.

In [22]:
LowerTriangular(A)


5×5 LowerTriangular{Int64, Matrix{Int64}}:
  4  ⋅  ⋅  ⋅  ⋅
 10  1  ⋅  ⋅  ⋅
  6  8  8  ⋅  ⋅
 10  5  9  8  ⋅
  4  7  9  2  8

The values along the main
diagonal can be converted to unity.

In [23]:
UnitUpperTriangular(A)

5×5 UnitUpperTriangular{Int64, Matrix{Int64}}:
 1  2  9  8  3
 ⋅  1  7  3  9
 ⋅  ⋅  1  7  4
 ⋅  ⋅  ⋅  1  2
 ⋅  ⋅  ⋅  ⋅  1

The same can be done for a lower
triangular view.

In [24]:
UnitLowerTriangular(A)

5×5 UnitLowerTriangular{Int64, Matrix{Int64}}:
  1  ⋅  ⋅  ⋅  ⋅
 10  1  ⋅  ⋅  ⋅
  6  8  1  ⋅  ⋅
 10  5  9  1  ⋅
  4  7  9  2  1

Diagonal matrices can be created as
proper diagonal as well as upper and
lower bidiagonal matrices.  The
Diagonal() function creates a diagonal
matrix.

In [25]:
d =Diagonal([1, 2, 3])


3×3 Diagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  3

Note that the result is a sparse array.


An upper bidiagonal matrix is created below.
Note the use of the :U symbol.

In [26]:
Bidiagonal([1, 2, 3, 4], [7, 8, 9], :U)


4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  7  ⋅  ⋅
 ⋅  2  8  ⋅
 ⋅  ⋅  3  9
 ⋅  ⋅  ⋅  4

A lower bidiagonal matrix uses the :L symbol.

In [27]:
Bidiagonal([1, 2, 3, 4], [7, 8, 9], :L)


4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 7  2  ⋅  ⋅
 ⋅  8  3  ⋅
 ⋅  ⋅  9  4

A bidiagonal matrix can be created from an existing array.

In [28]:
Random.seed!(1);
A = rand((1:5), (4, 4))

4×4 Matrix{Int64}:
 1  5  4  2
 2  1  1  1
 4  4  3  3
 4  4  3  4

In [29]:
Random.rand!([1,3])

2-element Vector{Int64}:
 3610739463416357436
  229882327607648703

In [93]:
rand(`(1:5), (4, 4))


4×4 Matrix{Int64}:
 5  1  4  3
 4  3  3  1
 2  1  5  1
 4  5  2  5

An upper bidiagonal version of A


In [30]:
Bidiagonal(A, :U)


4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  5  ⋅  ⋅
 ⋅  1  1  ⋅
 ⋅  ⋅  3  3
 ⋅  ⋅  ⋅  4

A lower bidiagonal version of A


In [31]:
Bidiagonal(A, :L)


4×4 Bidiagonal{Int64, Vector{Int64}}:
 1  ⋅  ⋅  ⋅
 2  1  ⋅  ⋅
 ⋅  4  3  ⋅
 ⋅  ⋅  3  4

We can also create a symmetric tridiagonal matrix.

In [32]:
SymTridiagonal([1, 2, 3, 4], [1, 1, 1])


4×4 SymTridiagonal{Int64, Vector{Int64}}:
 1  1  ⋅  ⋅
 1  2  1  ⋅
 ⋅  1  3  1
 ⋅  ⋅  1  4

Symmetric matrices can be constructed from existing matrices

In [34]:
Random.seed!(12)
A = rand(1:10, 5, 5)

5×5 Matrix{Int64}:
  4  2  9  8  3
 10  1  7  3  9
  6  8  8  7  4
 10  5  9  8  2
  4  7  9  2  8

In [37]:
Symmetric(A) # Construct from upper triangular elements (default).


5×5 Symmetric{Int64, Matrix{Int64}}:
 4  2  9  8  3
 2  1  7  3  9
 9  7  8  7  4
 8  3  7  8  2
 3  9  4  2  8

In [38]:
# Construct from lower triangular values.
Symmetric(A, :L)


5×5 Symmetric{Int64, Matrix{Int64}}:
  4  10  6  10  4
 10   1  8   5  7
  6   8  8   9  9
 10   5  9   8  2
  4   7  9   2  8

The transpose of a symmetric matrix is equal to itself.

In [39]:
Symmetric(A, :L) == Transpose(Symmetric(A, :L))


true

Hermitian matrices can be construicted from the upper or lower triangualr values of a matrix.

In [41]:
A = [
    1 0 2 + 2im 0 3 - 3im
    0 4 0 5 0
    6 - 6im 0 7 0 8 + 8im
    0 9 0 1 0
    2 + 2im 0 3 - 3im 0 4
]

5×5 Matrix{Complex{Int64}}:
 1+0im  0+0im  2+2im  0+0im  3-3im
 0+0im  4+0im  0+0im  5+0im  0+0im
 6-6im  0+0im  7+0im  0+0im  8+8im
 0+0im  9+0im  0+0im  1+0im  0+0im
 2+2im  0+0im  3-3im  0+0im  4+0im

In [42]:
Hermitian(A)


5×5 Hermitian{Complex{Int64}, Matrix{Complex{Int64}}}:
 1+0im  0+0im  2+2im  0+0im  3-3im
 0+0im  4+0im  0+0im  5+0im  0+0im
 2-2im  0+0im  7+0im  0+0im  8+8im
 0+0im  5+0im  0+0im  1+0im  0+0im
 3+3im  0+0im  8-8im  0+0im  4+0im

In [43]:
Hermitian(A, :L) # We can specify the lower values.

5×5 Hermitian{Complex{Int64}, Matrix{Complex{Int64}}}:
 1+0im  0+0im  6+6im  0+0im  2-2im
 0+0im  4+0im  0+0im  9+0im  0+0im
 6-6im  0+0im  7+0im  0+0im  3+3im
 0+0im  9+0im  0+0im  1+0im  0+0im
 2+2im  0+0im  3-3im  0+0im  4+0im


### Vector multiplication
 ---------------------

In [44]:
# The dot() function performs a dot product of same-sized vectors
dot([1, 2, 3], [2, 2, 2])

12

In [59]:
# Short-hand notation is available
[1, 2, 3]⋅[2, 2, 2]

12

In [60]:
# The cross() function determines vector cross-products
cross([1, 2, 3], [2, 2, 2])


3-element Vector{Int64}:
 -2
  4
 -2

In [61]:
# Short-hand notation is available as well.
[1, 2, 3] × [2, 2, 2]

3-element Vector{Int64}:
 -2
  4
 -2

### Matrix multiplication
---------------------

Matrix multiplication is calculated using the * symbol.


In [64]:
A = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [65]:
B = [1 2; 4 7; 2 3]

3×2 Matrix{Int64}:
 1  2
 4  7
 2  3

In [66]:
A * B

2×2 Matrix{Int64}:
 15  25
 36  61

In [70]:
# Matrix-vector multiplication is done in a similar way.

In [73]:
A = rand(1:10, 3, 3)

3×3 Matrix{Int64}:
 3  5  10
 7  8   3
 3  9   5

In [74]:
x = [1, 2, 3]


3-element Vector{Int64}:
 1
 2
 3

In [75]:
A * x


3-element Vector{Int64}:
 43
 32
 36

In [76]:
# Scalar-matrix like-wise uses the * symbol.
3 * A

3×3 Matrix{Int64}:
  9  15  30
 21  24   9
  9  27  15

In [ ]:
# Elemntwise matrix-matrix multiplication uses the .* notation.


In [77]:
B = rand(1:10, 3, 3)


3×3 Matrix{Int64}:
 7  1  10
 9  4   3
 3  1   6

In [78]:
A .* B

3×3 Matrix{Int64}:
 21   5  100
 63  32    9
  9   9   30

3×3 Matrix{Int64}:
 30  50  100
 70  80   30
 30  90   50

In [85]:
# Addition and subtraction are element-wise.
A + B

3×3 Matrix{Int64}:
 10   6  20
 16  12   6
  6  10  11

In [86]:
A

3×3 Matrix{Int64}:
 3  5  10
 7  8   3
 3  9   5

The UniformScaling() function creates an identity matrix or given scalar multiple of the identity matrix with a size as required.

In [87]:
UniformScaling(10) * A

3×3 Matrix{Int64}:
 30  50  100
 70  80   30
 30  90   50

In [88]:
A = [1 2 3 4; 2 3 4 5; 2 1 3 1]


3×4 Matrix{Int64}:
 1  2  3  4
 2  3  4  5
 2  1  3  1

In [90]:
UniformScaling(1) 

UniformScaling{Int64}
1*I

### Factorization
-----------


In [91]:

# Matrix factorization is commonly
# used for performance or memory
# optimization.
A = [1.5 2 -4; 2 -1 -3; -4 -3 5]

factorize(A)

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [92]:
A

3×3 Matrix{Float64}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

In [96]:
z = factorize(A)

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [94]:
det(A)

23.0

In [98]:
 z

BunchKaufman{Float64, Matrix{Float64}, Vector{Int64}}
D factor:
3×3 Tridiagonal{Float64, Vector{Float64}}:
 -1.64286   0.0   ⋅ 
  0.0      -2.8  0.0
   ⋅        0.0  5.0
U factor:
3×3 UnitUpperTriangular{Float64, Matrix{Float64}}:
 1.0  0.142857  -0.8
  ⋅   1.0       -0.6
  ⋅    ⋅         1.0
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [99]:
eigvals(A)

3-element Vector{Float64}:
 -2.310376890836094
 -1.115327714990029
  8.925704605826123